# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bf0b970b086e52802aa32f7b800d648ed3649f05ffae8681e78adff9db9d668434849c0aa995eb658ea1b6ca24b777410a4050941ec8143d5cf838ce8d37b7

test:
  secret_key_base: 5ce385a77e0cefab82704b303473f16ce99be79f2c0be554d07bdee4d6e2abf9bca7c45b949cc9f98784b6505b638a5d70a7eeed9dfe7fb3c2f3c28431b2fac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
